### ISSUE TITLE
Choosing a web framework

### ISSUE THREAD

**Issue by cmelone** [spack/spack-gantry#2]
## Problem/Opportunity Statement

An initial feature of Gantry will be to facilitate the collection of data about Spack CI runs and host an API that returns estimated resource utilization for a future job. In order to perform these functions, we will run an HTTP server that has the following requirements:

- no bloated MVC framework like Django
- easy access to a file-based database (eg SQLite)
- trivial background job support -- ideally no need to set up Redis or a similar service
- good support, documentation, and community

@alecbcs if there are any requirements you can think of please comment

## What would success / a fix look like?

Options:
- [AIOHTTP](https://docs.aiohttp.org/en/stable/index.html): very straightforward, seems like it requires a message queue backend for background tasks?
- [Litestar](https://litestar.dev): looks good and has lots of features, maybe too much (ORM support)
- [Starlette](https://www.starlette.io): lower level version of Litestar
- [Flask](https://flask.palletsprojects.com/en/3.0.x/): I am personally not a _huge_ fan

**Comment by cmelone** [comment]
spackbot seems to use `aiohttp` seamlessly

**Comment by alecbcs** [comment]
> - [AIOHTTP](https://docs.aiohttp.org/en/stable/index.html): very straightforward, seems like it requires a message queue backend for background tasks?

@cmelone what do you mean by background tasks? In @spackbot we handle longer running operations via `asyncio` functions that are called by a `aiohttp` handlers. In that use case the handlers may return a 200 status code and exit while still allowing the long running process to happen asynchronously in the background. 

If you think we could do the same here, I'd be in favor of trying out `aiohttp` without a proper message queue.

**Comment by cmelone** [comment]
Sounds good to me, I’m happy with this choice as well.
